sudo: required 
dist: trusty 
language: generic 

notifications:
  email:
    on_success: always
    on_failure: always
#    recipients:
#      - jane@doe
env:
  global:
    - ROS_PARALLEL_TEST_JOBS=-j1
  matrix:
    - ROS_DISTRO="indigo" ROS_REPO=ros
    - ROS_DISTRO="indigo" ROS_REPO=ros-shadow-fixed
    - ROS_DISTRO="jade"   ROS_REPO=ros
    - ROS_DISTRO="jade"   ROS_REPO=ros-shadow-fixed
matrix:
  allow_failures:
    - env: ROS_DISTRO="jade"   ROS_REPO=ros
    - env: ROS_DISTRO="jade"   ROS_REPO=ros-shadow-fixed
install:
  - git clone https://github.com/ros-industrial/industrial_ci.git .ci_config
script: 
  - .ci_config/travis.sh
