#!/usr/bin/env python
   
from industrial_robot_pkg_gen.cmd_line_interface import *


if __name__ == '__main__':

  cli = CmdLineInterface()
  cli.add_sub_cmd(SupportSubCmd())
  cli.add_sub_cmd(MoveitSubCmd())
  cli.run()
